name: ms-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: windows-latest

    env:
      PROJECT_FILE_PATH: build/hotcorners.vcxproj
      BUILD_CONFIGURATION: Release
      BUILD_PLATFORM: x64

    steps:
    - uses: actions/checkout@v5

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v3

    - name: Build-App
      shell: pwsh
      run: >
        msbuild "$env:PROJECT_FILE_PATH"
        -t:Rebuild
        -m
        -p:Configuration=$env:BUILD_CONFIGURATION
        -p:Platform=$env:BUILD_PLATFORM
        -p:WindowsTargetPlatformVersion=10.0
